# Generated by Django 3.2.9 on 2023-02-15 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubajedrez',
            name='population',
            field=models.CharField(blank=True, max_length=100, verbose_name='población'),
        ),
        migrations.AddField(
            model_name='clubajedrez',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='Código Postal'),
        ),
    ]
