# Generated by Django 3.2.9 on 2022-10-01 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20220922_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentregistration',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.torneo', verbose_name='registros'),
        ),
    ]
