# Generated by Django 3.2.9 on 2022-11-16 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normativa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='circular',
            name='search_date',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
