# Generated by Django 3.2.9 on 2023-02-27 17:23

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normativa', '0002_circular_search_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circular',
            name='file_pdf',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='pdf/%Y/%m/%d/', verbose_name='circulares'),
        ),
    ]
