# Generated by Django 3.2.9 on 2023-02-14 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circuitos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='registrationtournamentdiputacion',
            name='unique_registrationtournamentdiputacion',
        ),
        migrations.AddConstraint(
            model_name='registrationtournamentdiputacion',
            constraint=models.UniqueConstraint(fields=('name', 'surnames', 'date_birth', 'tournament_title'), name='unique_registrationtournamentdiputacion'),
        ),
    ]
